kind: Service
apiVersion: v1

metadata:
  name: notes-app-service
  namespace: python-django

spec:
  selector:
    app: python-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
